name: "✨ Feature Request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ### ✨ Feature Request
        *How would you improve our project?*
        
        **Preview of your request:**
        ---
        **Description**: [your input]
        **Why Needed**: [your input]
        **Proposed Solution**: [your input]
        ---

  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      placeholder: "What should we add or improve?"
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: "Why is this needed?"
      placeholder: "What problem does this solve?"

  - type: textarea
    id: solution
    attributes:
      label: "Proposed Solution"
      placeholder: "How should this work?"

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I've checked this doesn't exist already"
          required: true
        - label: "I'm willing to help implement this"